---
- name: "Copy BashRC"
  copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}"

- name: "Read current mate terminal profiles"
  dconf:
    key: "/org/mate/terminal/global/profile-list"
    state: "read"
  register: "profile_list"

- name: "profile_list was not set, setting"
  set_fact:
    profile_list: 
      value: '["default"]'
  when: profile_list.value is none

- name: "Adding our profile"
  set_fact:
    new_profile_list: "{{ profile_list.value | regex_replace(']$', \", 'muli']\") }}"

- name: "Writing updated profile list"
  dconf:
    key: "/org/mate/terminal/global/profile-list"
    value: "{{ new_profile_list }}"
  when: "'muli' not in profile_list.value"
  
- name: "Restoring MULI Profile from Dump"
  shell:
    cmd: "dconf load /org/mate/terminal/profiles/muli/ < {{ role_path }}/files/dconf-dump-muli"
  when: "'muli' not in profile_list.value"
